### ISSUE TITLE
CARTA gRPC service failed to start

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#25]
If we do
`session = Session.new(ChromeHeadless())`
without an ending 
`session.close()`
in the end of the script,

next time we run the script we will see

> python3 test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    session = Session.new(ChromeHeadless())
  File "/home/kswang/.local/lib/python3.8/site-packages/carta/client.py", line 150, in new
    return browser.new_session_with_backend(executable_path, grpc_port, remote_host, params, timeout, token)
  File "/home/kswang/.local/lib/python3.8/site-packages/carta/browser.py", line 229, in new_session_with_backend
    self.exit(f"CARTA backend exited unexpectedly:\n{''.join(backend.errors)}")
  File "/home/kswang/.local/lib/python3.8/site-packages/carta/browser.py", line 261, in exit
    raise CartaScriptingException(msg)
carta.util.CartaScriptingException: CARTA backend exited unexpectedly:
[2021-10-06 21:04:47.358] [critical] CARTA gRPC service failed to start. Could not bind to port 50051. Aborting.

**Comment by veggiesaurus** [comment]
@confluence can we close this?

**Comment by confluence** [comment]
Yes; it's definitely no longer relevant.
