### ISSUE TITLE
cannot get image header due to HISTORY

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#44]
```
    @cached
    def header(self):
        """The header of the image.

        Returns
        -------
        dict of string to string, integer, float or boolean
            The header of the image, with field names as keys. T or F string values are automatically converted to booleans.
        """
        raw_header = self.get_value("frameInfo.fileInfoExtended.headerEntries")
        header = {e["name"]: e.get("numericValue", e["value"]) for e in raw_header}
        for k, v in header.items():
            if v == 'T':
                header[k] = True
            elif v == 'F':
                header[k] = False
        return header
```
of the `Image` class needs a fix for the HISTORY in the `raw_header`.

The example `raw_header` causing the issue is like

```
{'entryType': 'FLOAT', 'name': 'OBSGEO-Z', 'numericValue': -2481029.851874, 'value': '-2.481029851874E+06'}
{'comment': 'Date FITS file was written', 'name': 'DATE', 'value': '2019-04-02T02:49:20.966000'}
{'name': 'ORIGIN', 'value': 'CASA 5.3.0-143'}
{'name': 'HISTORY CASA START LOGTABLE'}
```

as there is only 'name' but no 'value' in `{'name': 'HISTORY CASA START LOGTABLE'}`.

trackback
```
Traceback (most recent call last):
  File "/Users/kswang/carta_pythonInterface_testing/test.py", line 6, in <module>
    print(img0.header)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/util.py", line 113, in newfunc
    self._cache[func.__name__] = func(self, *args)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/image.py", line 163, in header
    header = {e["name"]: e.get("numericValue", e["value"]) for e in raw_header}
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/image.py", line 163, in <dictcomp>
    header = {e["name"]: e.get("numericValue", e["value"]) for e in raw_header}
KeyError: 'value'
```

**Comment by veggiesaurus** [comment]
@confluence `value` is optional. For example, `COMMENT` and `HISTORY` have no value
