### ISSUE TITLE
image.close() hangs if the image is the spatial reference image and there are images matched to it

### ISSUE THREAD

**Issue by kswang1029** [idia-astro/carta-python#47]
```
from carta.session import Session

session = Session.interact("http://localhost:3002/?token=0C0095EE-7B6F-42D5-83AD-B2F96763AEA1", 2866182134)
img0 = session.open_image("/Users/kswang/carta_image_pool/spire250_ext.fits")
img1 = session.append_image("/Users/kswang/carta_image_pool/spire350_ext.fits")

img0.make_active()
img1.set_spatial_matching(True)
img0.close()
```

When the spatial reference image is being closed where there are images matched to it, the frontend pops up a dialog to warn users that images will be unmatched and asks for a OK or Cancel. When doing this with the scripting interface, the execution hangs for a while and died with 

```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/anaconda3/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/opt/anaconda3/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/opt/anaconda3/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/anaconda3/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/anaconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=3002): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/protocol.py", line 348, in request_scripting_action
    response = requests.post(url=self.base_url + self.ACTION_PATH, data=request_data, headers=headers, timeout=timeout)
  File "/opt/anaconda3/lib/python3.9/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 578, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='localhost', port=3002): Read timed out. (read timeout=10)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kswang/carta_pythonInterface_testing/test.py", line 10, in <module>
    img0.close()
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/image.py", line 594, in close
    self.session.call_action("closeFile", self._frame)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/session.py", line 196, in call_action
    return self._protocol.request_scripting_action(self.session_id, path, *args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/carta/protocol.py", line 350, in request_scripting_action
    raise CartaBadRequest(f"{carta_action_description} failed: {e}") from e
carta.util.CartaBadRequest: CARTA scripting action .closeFile called with parameters (Macro('', 'frameMap[38]'),) failed: HTTPConnectionPool(host='localhost', port=3002): Read timed out. (read timeout=10)
```

If we click OK (in the interact mode) in time, the script terminated peacefully.

**Comment by confluence** [comment]
Looks like there's a parameter to bypass that dialog. Should be a quick fix.
